### ISSUE TITLE
Error Invalid environment; fetch is not defined

### ISSUE THREAD

**Issue by AllahPower** [Elitezen/discordjs-chatgpt#1]
file:///C:/Users/***/Desktop/cekret/dickcord/***_bot/node_modules/chatgpt/build/index.js:150
      throw new Error("Invalid environment; fetch is not defined");
            ^

Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///C:/Users/***/Desktop/cekret/dickcord/***_bot/node_modules/chatgpt/build/index.js:150:13)
    at ChatGPTClient.<anonymous> (C:\Users\***\Desktop\cekret\dickcord\***_bot\node_modules\discordjs-chatgpt\src\ChatGPTClient.js:29:24)

**Comment by AllahPower** [comment]
Fix -> Im update nodeJs v16 -> v19
